apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: vdqh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vdqh
    app.kubernetes.io/part-of: byoc-app-avid
  name: vdqh
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: vdqh
status:
  loadBalancer: {}
